test1_power_allocation:
  env_id: ENVIRONMENT-v1
  replay_memory_size: 100000
  batch_size: 64
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.05
  network_sync_rate: 1000
  alpha: 0.001
  gamma: 0.4
  stop_on_reward: 1_000_000_000
  hidden_dims: [256,512,256]
  env_params:
    data_file: 1
    mode: power_allocation

test1_resource_allocation:
  env_id: ENVIRONMENT-v1
  replay_memory_size: 100000
  batch_size: 64
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.05
  network_sync_rate: 1000
  alpha: 0.001
  gamma: 0.4
  stop_on_reward: 1_000_000_000
  hidden_dims: [256,512,256]
  env_params:
    data_file: 1
    mode: resource_allocation


test2_power_allocation:
  env_id: ENVIRONMENT-v1
  replay_memory_size: 100000
  batch_size: 64
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.01
  network_sync_rate: 1000
  alpha: 0.001
  gamma: 0.4
  stop_on_reward: 1_000_000_000
  hidden_dims: [256,512,256]
  env_params:
    data_file: 2
    mode: power_allocation

test2_resource_allocation:
  env_id: ENVIRONMENT-v1
  replay_memory_size: 100000
  batch_size: 64
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.01
  network_sync_rate: 1000
  alpha: 0.001
  gamma: 0.4
  stop_on_reward: 1_000_000_000
  hidden_dims: [256,512,256]
  env_params:
    data_file: 2
    mode: resource_allocation


test3_power_allocation:
  env_id: ENVIRONMENT-v1
  replay_memory_size: 100000
  batch_size: 64
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.01
  network_sync_rate: 1000
  alpha: 0.001
  gamma: 0.4
  stop_on_reward: 1_000_000_000
  hidden_dims: [256, 512, 256]
  env_params:
    data_file: 3
    mode: power_allocation

test3_resource_allocation:
  env_id: ENVIRONMENT-v1
  replay_memory_size: 100000
  batch_size: 128
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.01
  network_sync_rate: 1000
  alpha: 0.001
  gamma: 0.4
  stop_on_reward: 1_000_000_000
  hidden_dims: [256,512,256]
  env_params:
    data_file: 3
    mode: resource_allocation


test4_power_allocation:
  env_id: ENVIRONMENT-v1
  replay_memory_size: 100000
  batch_size: 64
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.01
  network_sync_rate: 500
  alpha: 0.00001
  gamma: 0.99
  stop_on_reward: 1_000_000_000
  hidden_dims: [256]
  env_params:
    data_file: 4
    mode: power_allocation

test4_resource_allocation:
  env_id: ENVIRONMENT-v1
  replay_memory_size: 100000
  batch_size: 64
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.01
  network_sync_rate: 500
  alpha: 0.00001
  gamma: 0.99
  stop_on_reward: 1_000_000_000
  hidden_dims: [256]
  env_params:
    data_file: 4
    mode: resource_allocation


test5_power_allocation:
  env_id: ENVIRONMENT-v1
  replay_memory_size: 100000
  batch_size: 64
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.01
  network_sync_rate: 500
  alpha: 0.00001
  gamma: 0.99
  stop_on_reward: 1_000_000_000
  hidden_dims: [256]
  env_params:
    data_file: 5
    mode: power_allocation

test5_resource_allocation:
  env_id: ENVIRONMENT-v1
  replay_memory_size: 100000
  batch_size: 64
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.01
  network_sync_rate: 500
  alpha: 0.00001
  gamma: 0.99
  stop_on_reward: 1_000_000_000
  hidden_dims: [256]
  env_params:
    data_file: 5
    mode: resource_allocation


test6_power_allocation:
  env_id: ENVIRONMENT-v1
  replay_memory_size: 100000
  batch_size: 64
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.01
  network_sync_rate: 500
  alpha: 0.00001
  gamma: 0.99
  stop_on_reward: 1_000_000_000
  hidden_dims: [256]
  env_params:
    data_file: 6
    mode: power_allocation

test6_resource_allocation:
  env_id: ENVIRONMENT-v1
  replay_memory_size: 100000
  batch_size: 64
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.01
  network_sync_rate: 500
  alpha: 0.00001
  gamma: 0.99
  stop_on_reward: 1_000_000_000
  hidden_dims: [256]
  env_params:
    data_file: 6
    mode: resource_allocation
    

test7_power_allocation:
  env_id: ENVIRONMENT-v1
  replay_memory_size: 100000
  batch_size: 64
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.01
  network_sync_rate: 500
  alpha: 0.00001
  gamma: 0.99
  stop_on_reward: 1_000_000_000
  hidden_dims: [256]
  env_params:
    data_file: 7
    mode: power_allocation

test7_resource_allocation:
  env_id: ENVIRONMENT-v1
  replay_memory_size: 100000
  batch_size: 64
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.01
  network_sync_rate: 500
  alpha: 0.00001
  gamma: 0.99
  stop_on_reward: 1_000_000_000
  hidden_dims: [256]
  env_params:
    data_file: 7
    mode: resource_allocation